<?php
session_start(); include('check-login.php'); include_once('club-utils.php'); club_ensure_tables($con);
$uid=$_SESSION['USERID']??''; $club=trim($_GET['club']??$_POST['club']??''); $c=club_detail($con,$club); $admin=club_is_admin(); $member=club_member($con,$club,$uid); $leader=$c && $c['leaderid']===$uid;
if(!$c || (!$admin && !$member && !$leader)){ http_response_code(403); exit('This is a private club room. Only approved members can enter.'); }
$notice='';
if(isset($_POST['send']) && ($member||$leader)){ $text=trim($_POST['text']??''); if($text!==''){ $id=club_id('MSG');$ce=mysqli_real_escape_string($con,$club);$ue=mysqli_real_escape_string($con,$uid);$te=mysqli_real_escape_string($con,substr($text,0,3000));mysqli_query($con,"INSERT INTO tblclubmessage(messageid,clubid,senderid,messagetext,sentat) VALUES('$id','$ce','$ue','$te',NOW())");club_log($con,$club,$uid,$uid,'sent message'); } header('location:club-room.php?club='.rawurlencode($club));exit; }
if($leader && isset($_POST['membership'])){ $target=trim($_POST['userid']??'');$action=$_POST['membership'];$ce=mysqli_real_escape_string($con,$club);$te=mysqli_real_escape_string($con,$target); if($action==='approve'){$role='member';mysqli_query($con,"UPDATE tblclubmember SET status='active',updatedat=NOW() WHERE clubid='$ce' AND userid='$te'");club_log($con,$club,$target,$uid,'approved membership');$notice='Member approved.';} if($action==='remove') {mysqli_query($con,"UPDATE tblclubmember SET status='removed',updatedat=NOW() WHERE clubid='$ce' AND userid='$te'");club_log($con,$club,$target,$uid,'removed member');$notice='Member removed from the private group.';} }
$ce=mysqli_real_escape_string($con,$club);$messages=mysqli_query($con,"SELECT m.*,CONCAT_WS(' ',u.firstname,u.othernames,u.surname) sendername FROM tblclubmessage m LEFT JOIN tblsystemuser u ON u.userid=m.senderid WHERE m.clubid='$ce' AND m.status='active' ORDER BY m.sentat ASC");$members=mysqli_query($con,"SELECT m.*,CONCAT_WS(' ',u.firstname,u.othernames,u.surname) name FROM tblclubmember m LEFT JOIN tblsystemuser u ON u.userid=m.userid WHERE m.clubid='$ce' AND m.status IN ('active','pending') ORDER BY m.status DESC,m.joinedat DESC");$backPage=$admin ? 'club-admin.php' : 'clubs.php';
?>
<!doctype html><html><head><?php include('links.php');?><link rel="stylesheet" href="css/clubs.css"></head><body class="clubs-page"><div class="header"><?php include('menu.php');?></div><main class="clubs-wrap"><a class="clubs-back" href="<?php echo $backPage;?>"><i class="fa fa-arrow-left"></i> Back to clubs</a><section class="room-head"><span>PRIVATE MEMBER SPACE</span><h1><?php echo club_esc($c['clubname']);?></h1><p><?php echo club_esc($c['description']);?></p></section><?php if($notice){?><div class="clubs-msg"><?php echo club_esc($notice);?></div><?php } ?><div class="room-layout"><section class="chat-box"><div class="chat-box__head"><strong><i class="fa fa-lock"></i> Members-only chat</strong><?php if($admin){?><em>Administrator view</em><?php } ?></div><div class="messages"><?php while($m=mysqli_fetch_assoc($messages)){ $mine=$m['senderid']===$uid; $sender=trim($m['sendername']) ? trim($m['sendername']) : $m['senderid']; ?><article class="bubble <?php echo $mine ? 'bubble--mine' : '';?>"><b><?php echo club_esc($sender);?></b><p><?php echo nl2br(club_esc($m['messagetext']));?></p><small><?php echo date('g:i a',strtotime($m['sentat']));?></small></article><?php } ?></div><?php if(!$admin){?><form method="post" class="chat-send"><input type="hidden" name="club" value="<?php echo club_esc($club);?>"><input name="text" maxlength="3000" required placeholder="Share an idea with the crew..."><button name="send"><i class="fa fa-paper-plane"></i></button></form><?php } ?></section><aside class="member-box"><h2><i class="fa fa-users"></i> The crew</h2><?php while($m=mysqli_fetch_assoc($members)){ $memberName=trim($m['name']) ? trim($m['name']) : $m['userid']; ?><div class="member"><span><?php echo club_esc($memberName);?> <?php echo $m['userid']===$c['leaderid']?'Leader':'';?></span><small><?php echo club_esc($m['status']);?></small><?php if($leader && $m['userid']!==$uid){?><form method="post"><input type="hidden" name="club" value="<?php echo club_esc($club);?>"><input type="hidden" name="userid" value="<?php echo club_esc($m['userid']);?>"><?php if($m['status']==='pending'){?><button name="membership" value="approve">Approve</button><?php } else {?><button name="membership" value="remove">Remove</button><?php } ?></form><?php } ?></div><?php } ?></aside></div></main></body></html>
