<?php
/* Clubs are deliberately separate from student-to-student chat: every access check
   below is membership based, so a club discussion can never become school-wide. */
if(!function_exists('club_esc')){ function club_esc($v){ return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); } }
if(!function_exists('club_id')){ function club_id($p='CLB'){ return $p.date('YmdHis').substr(bin2hex(random_bytes(6)),0,10); } }
if(!function_exists('club_is_admin')){ function club_is_admin(){ return isset($_SESSION['ACCESSLEVEL']) && $_SESSION['ACCESSLEVEL']==='administrator'; } }
if(!function_exists('club_is_student')){ function club_is_student(){ return isset($_SESSION['ACCESSLEVEL'],$_SESSION['SYSTEMTYPE']) && $_SESSION['ACCESSLEVEL']==='user' && $_SESSION['SYSTEMTYPE']==='Student'; } }
if(!function_exists('club_ensure_tables')){ function club_ensure_tables($con){
 mysqli_query($con,"CREATE TABLE IF NOT EXISTS tblclub (clubid VARCHAR(40) PRIMARY KEY, clubname VARCHAR(100) NOT NULL, description TEXT NULL, leaderid VARCHAR(30) NOT NULL, status VARCHAR(15) NOT NULL DEFAULT 'active', createdby VARCHAR(30) NOT NULL, createdat DATETIME NOT NULL, updatedat DATETIME NULL, KEY idx_club_leader(leaderid), KEY idx_club_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 mysqli_query($con,"CREATE TABLE IF NOT EXISTS tblclubmember (memberid VARCHAR(40) PRIMARY KEY, clubid VARCHAR(40) NOT NULL, userid VARCHAR(30) NOT NULL, role VARCHAR(15) NOT NULL DEFAULT 'member', status VARCHAR(15) NOT NULL DEFAULT 'pending', addedby VARCHAR(30) NOT NULL, joinedat DATETIME NOT NULL, updatedat DATETIME NULL, UNIQUE KEY uq_club_member(clubid,userid), KEY idx_member_user(userid,status), KEY idx_member_club(clubid,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 mysqli_query($con,"CREATE TABLE IF NOT EXISTS tblclubmessage (messageid VARCHAR(40) PRIMARY KEY, clubid VARCHAR(40) NOT NULL, senderid VARCHAR(30) NOT NULL, messagetext TEXT NOT NULL, status VARCHAR(15) NOT NULL DEFAULT 'active', readat DATETIME NULL, sentat DATETIME NOT NULL, KEY idx_clubmessage(clubid,sentat), KEY idx_clubsender(senderid)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 mysqli_query($con,"CREATE TABLE IF NOT EXISTS tblclubaudit (auditid VARCHAR(40) PRIMARY KEY, clubid VARCHAR(40) NOT NULL, userid VARCHAR(30) NULL, actorid VARCHAR(30) NOT NULL, action VARCHAR(60) NOT NULL, detail VARCHAR(255) NULL, datetimeentry DATETIME NOT NULL, KEY idx_clubaudit(clubid,datetimeentry)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
} }
if(!function_exists('club_log')){ function club_log($con,$club,$user,$actor,$action,$detail=''){ $c=mysqli_real_escape_string($con,$club);$u=mysqli_real_escape_string($con,$user);$a=mysqli_real_escape_string($con,$actor);$x=mysqli_real_escape_string($con,$action);$d=mysqli_real_escape_string($con,substr($detail,0,255)); mysqli_query($con,"INSERT INTO tblclubaudit VALUES ('".club_id('AUD')."','$c','".$u."','$a','$x','$d',NOW())"); } }
if(!function_exists('club_member')){ function club_member($con,$club,$user){ $c=mysqli_real_escape_string($con,$club);$u=mysqli_real_escape_string($con,$user);$r=mysqli_query($con,"SELECT * FROM tblclubmember WHERE clubid='$c' AND userid='$u' AND status='active' LIMIT 1"); return $r?mysqli_fetch_assoc($r):null; } }
if(!function_exists('club_detail')){ function club_detail($con,$club){ $c=mysqli_real_escape_string($con,$club);$r=mysqli_query($con,"SELECT c.*, CONCAT_WS(' ',u.firstname,u.othernames,u.surname) leadername FROM tblclub c LEFT JOIN tblsystemuser u ON u.userid=c.leaderid WHERE c.clubid='$c' LIMIT 1");return $r?mysqli_fetch_assoc($r):null;} }
if(!function_exists('club_name')){ function club_name($con,$id){$i=mysqli_real_escape_string($con,$id);$r=mysqli_query($con,"SELECT CONCAT_WS(' ',firstname,othernames,surname) n FROM tblsystemuser WHERE userid='$i' LIMIT 1");$x=$r?mysqli_fetch_assoc($r):null; return trim($x['n']??'')?:$id;} }
