<?php /* Ayirebi Senior High School privacy and safeguarding notice */ ?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Ayirebi Senior High School privacy, student images and safeguarding notice.">
  <title>Privacy & Safeguarding | Ayirebi Senior High School</title>
  <link rel="icon" type="image/png" href="logo/logo-transparent.png">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="school-site.css">
  <link rel="stylesheet" href="css/ayisec-shared-palette.css">
  <style>.policy-page{background:#f6f4ee;min-height:100vh}.policy-header{background:var(--deep);color:#fff;padding:20px 0}.policy-header .brand{color:#fff}.policy-hero{padding:80px 0 52px;background:linear-gradient(135deg,#10203a,#17486d);color:#fff}.policy-hero h1{font:500 clamp(42px,6vw,68px)/1.02 "Playfair Display",serif;margin:0}.policy-hero p{max-width:600px;color:#d7e0e7;font-size:17px}.policy-content{width:min(880px,calc(100% - 40px));margin:0 auto;padding:65px 0 90px}.policy-content section{padding:28px 0;border-bottom:1px solid #d4dde3}.policy-content h2{font:500 29px "Playfair Display",serif;margin:0 0 12px;color:var(--ink)}.policy-content p,.policy-content li{color:#526775;line-height:1.75}.policy-content ul{padding-left:20px}.policy-contact{margin-top:38px;padding:24px;background:#e7eff2;border-left:4px solid var(--orange)}.policy-footer{padding:22px 0;background:#081a31;color:#b7c8c0;font-size:12px}@media(max-width:480px){.policy-hero{padding:62px 0 42px}.policy-content{padding:45px 0 70px}}</style>
</head>
<body class="policy-page">
  <header class="policy-header"><div class="shell"><a class="brand" href="website.php"><span class="crest"><img src="logo/logo-transparent.png" alt="Ayirebi Senior High School logo"></span><span><strong>Ayirebi</strong><small>Senior High School</small></span></a></div></header>
  <main><section class="policy-hero"><div class="shell"><p class="eyebrow light">Our commitment to families</p><h1>Privacy &<br><em>Safeguarding.</em></h1><p>We are committed to treating personal information, student images and family concerns with care and respect.</p></div></section><article class="policy-content"><section><h2>Privacy statement</h2><p>Ayirebi Senior High School uses information provided through its school systems, admissions processes and direct communications only for school-related purposes, including responding to enquiries, supporting admissions and managing student services.</p><p>We ask that visitors share only the information needed for their enquiry. Personal information is handled by authorised school personnel in line with school procedures and applicable requirements.</p></section><section><h2>Student images and school media</h2><p>This website may display images from school activities, achievements, sports, cultural events and community programmes. These images are used to celebrate school life and communicate AYISEC activities to our community.</p><p>If you are a parent, guardian, student or member of the public with a concern about an image, please contact the school promptly so that it can be reviewed.</p></section><section><h2>Third-party services</h2><p>For visitor convenience, this website links to Google Maps, WhatsApp, Facebook and TikTok. These services are operated independently and have their own privacy practices. Please review their policies before sharing information through those platforms.</p></section><section><h2>Safeguarding</h2><p>The safety and wellbeing of students is a priority. Any safeguarding concern should be reported directly to the school through a responsible staff member, the Headmaster, or the school’s official contact channels. In an emergency, contact the appropriate emergency services immediately.</p></section><section><h2>Your questions</h2><p>You may contact the school to ask about information held in connection with an enquiry, to raise a concern about website content, or to request review of an image appearing on this website.</p></section><div class="policy-contact"><strong>Contact Ayirebi Senior High School</strong><br>Ghana Post GPS: EM-0916-5753<br>P.O. Box 541, Akim Oda<br><a href="mailto:ayirebishs@ges.gov.gh">ayirebishs@ges.gov.gh</a></div></article></main>
  <footer class="policy-footer"><div class="shell">© 2026 Ayirebi Senior High School · <a href="website.php">Return to school website</a></div></footer>
</body>
</html>
