<?php
session_start(); require_once('check-login.php'); require_once('smartmark-utils.php'); smartmark_ensure_tables($con);
if(!(isset($_SESSION['ACCESSLEVEL'],$_SESSION['SYSTEMTYPE'])&&$_SESSION['ACCESSLEVEL']==='user'&&$_SESSION['SYSTEMTYPE']==='Teacher')){header('location:index.php');exit();}
$teacherId=(string)$_SESSION['USERID'];$teacherEsc=mysqli_real_escape_string($con,$teacherId);$assessmentId=(int)($_GET['assessment']??$_POST['assessmentid']??0);
$res=@mysqli_query($con,"SELECT * FROM tblsmartmarkassessment WHERE assessmentid=$assessmentId AND teacherid='$teacherEsc' AND status='active' LIMIT 1");$assessment=$res?mysqli_fetch_array($res,MYSQLI_ASSOC):null;if(!$assessment){header('location:smartmark.php');exit();}
if(empty($_SESSION['smartmark_csrf'])){$_SESSION['smartmark_csrf']=bin2hex(random_bytes(24));}$error='';$detected=null;
if($_SERVER['REQUEST_METHOD']==='POST' && hash_equals($_SESSION['smartmark_csrf'],$_POST['csrf']??'')){
 if(($_POST['action']??'')==='confirm'){$answers=$_POST['answerkey']??array();$key=array();foreach(range(1,(int)$assessment['questioncount']) as $n){$value=strtoupper(trim((string)($answers[$n]??'')));$key[$n]=in_array($value,smartmark_options($assessment['optioncount']),true)?$value:'';}if(in_array('',array_values($key),true)){$error='Select one answer for every question before confirming.';}else{$template=$_POST['template']??'{}';$stmt=mysqli_prepare($con,'UPDATE tblsmartmarkassessment SET answerkey=?,mastertemplate=?,masterconfirmed=1 WHERE assessmentid=? AND teacherid=?');$json=json_encode($key);mysqli_stmt_bind_param($stmt,'ssis',$json,$template,$assessmentId,$teacherId);$ok=mysqli_stmt_execute($stmt);mysqli_stmt_close($stmt);if($ok){header('location:smartmark.php?assessment='.$assessmentId);exit();}$error='The master template could not be saved.';}}
 else if(empty($_FILES['master_sheet'])||$_FILES['master_sheet']['error']!==UPLOAD_ERR_OK){$error='Upload the teacher’s shaded master sheet.';}
 else if(!function_exists('curl_init')){$error='PHP cURL is not enabled.';}
 else{$mime=(new finfo(FILEINFO_MIME_TYPE))->file($_FILES['master_sheet']['tmp_name']);if(!in_array($mime,array('image/jpeg','image/png','image/webp'),true)){$error='Use JPG, PNG, or WEBP.';}else{$config=require __DIR__.'/smartmark-service-config.example.php';if(file_exists(__DIR__.'/smartmark-service-config.local.php')){$config=require __DIR__.'/smartmark-service-config.local.php';}$curl=curl_init(rtrim((string)($config['url']??'http://127.0.0.1:8765'),'/').'/learn-template');$headers=!empty($config['token'])?array('X-SmartMark-Token: '.$config['token']):array();$post=array('image'=>new CURLFile($_FILES['master_sheet']['tmp_name'],$mime,$_FILES['master_sheet']['name']),'question_count'=>(int)$assessment['questioncount'],'option_count'=>(int)$assessment['optioncount']);curl_setopt_array($curl,array(CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$post,CURLOPT_HTTPHEADER=>$headers,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>30));$body=curl_exec($curl);$status=(int)curl_getinfo($curl,CURLINFO_HTTP_CODE);$curlError=curl_error($curl);curl_close($curl);$detected=json_decode((string)$body,true);if($body===false||$status!==200||!is_array($detected)){$error='Scanner unavailable: '.(is_array($detected)?($detected['detail']??'Unknown error'):$curlError);$detected=null;}}}
}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Master answer sheet</title><?php include('links.php'); ?><link rel="stylesheet" href="css/smartmark.css"></head><body class="smartmark-page"><main class="smartmark-shell"><a class="smartmark-back" href="smartmark.php?assessment=<?php echo $assessmentId;?>"><i class="fa fa-arrow-left"></i> Back to assessment</a><section class="smartmark-card"><div class="smartmark-heading"><div><span>Step 1: learn this sheet</span><h2>Upload master answer sheet</h2></div></div><?php if($error){?><div class="smartmark-flash smartmark-flash--error"><?php echo smartmark_escape($error);?></div><?php }?><?php if(!$detected){?><form method="post" enctype="multipart/form-data" class="smartmark-create"><input type="hidden" name="csrf" value="<?php echo smartmark_escape($_SESSION['smartmark_csrf']);?>"><label class="smartmark-file">Correctly shaded teacher sheet<input type="file" name="master_sheet" accept="image/jpeg,image/png,image/webp" required><small>Use the same standard sheet that students will complete.</small></label><div class="smartmark-empty">The scanner will straighten the image, learn the answer grid, and suggest the shaded correct answers. You confirm them before any student paper can be trusted.</div><button class="smartmark-primary"><i class="fa fa-camera"></i> Learn master sheet</button></form><?php }else{$answers=$detected['answers']??array();$template=json_encode($detected['template']??array());?><form method="post" class="smartmark-mark"><input type="hidden" name="csrf" value="<?php echo smartmark_escape($_SESSION['smartmark_csrf']);?>"><input type="hidden" name="action" value="confirm"><input type="hidden" name="assessmentid" value="<?php echo $assessmentId;?>"><input type="hidden" name="template" value="<?php echo smartmark_escape($template);?>"><div class="smartmark-answer-grid"><?php foreach(range(1,(int)$assessment['questioncount']) as $n){$row=$answers[(string)$n]??array();$selected=$row['selected'][0]??'';$confidence=(int)($row['confidence']??0);?><fieldset class="<?php echo (!empty($row['review'])||$confidence<80)?'smartmark-needs-review':'';?>"><legend>Q<?php echo $n;?> <small><?php echo $confidence;?>% confidence</small></legend><?php foreach(smartmark_options($assessment['optioncount']) as $option){?><label><input type="radio" name="answerkey[<?php echo $n;?>]" value="<?php echo $option;?>" <?php echo $option===$selected?'checked':'';?> required> <?php echo $option;?></label><?php }?></fieldset><?php }?></div><p class="smartmark-note">Check every highlighted item, correct any wrong selection, then confirm the master key.</p><button class="smartmark-primary"><i class="fa fa-check"></i> Confirm and save master template</button></form><?php }?></section></main></body></html>
