<?php
session_start(); require_once('check-login.php'); require_once('staff-permission-utils.php'); require_once('house-master-utils.php'); staff_permission_ensure_table($con);
$options=staff_permission_approver_options(); if(empty($options)){ http_response_code(403); exit('Your account cannot submit a staff permission request.'); }
if(empty($_SESSION['staff_permission_csrf'])){ $_SESSION['staff_permission_csrf']=bin2hex(random_bytes(32)); } $message=''; $tone='ok';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals($_SESSION['staff_permission_csrf'],isset($_POST['csrf'])?$_POST['csrf']:'')){ $message='Your form expired. Please try again.'; $tone='bad'; }
 else { $approver=isset($_POST['approver_role'])?$_POST['approver_role']:''; $type=trim(isset($_POST['permission_type'])?$_POST['permission_type']:''); $reason=trim(isset($_POST['reason'])?$_POST['reason']:''); $start=str_replace('T',' ',isset($_POST['start_datetime'])?$_POST['start_datetime']:''); $end=str_replace('T',' ',isset($_POST['end_datetime'])?$_POST['end_datetime']:''); if(!isset($options[$approver]) || $type==='' || $reason==='' || strtotime($start)===false || strtotime($end)===false || strtotime($end)<=strtotime($start)){ $message='Complete all fields and ensure the end time is after the start time.'; $tone='bad'; } else { $stmt=mysqli_prepare($con,"INSERT INTO tblstaffpermissionrequest (requester_id,approver_role,permission_type,reason,start_datetime,end_datetime) VALUES (?,?,?,?,?,?)"); $user=$_SESSION['USERID']; mysqli_stmt_bind_param($stmt,'ssssss',$user,$approver,$type,$reason,$start,$end); $ok=mysqli_stmt_execute($stmt); mysqli_stmt_close($stmt); if($ok){ $name=$_SESSION['USERID']; $person=mysqli_query($con,"SELECT firstname,othernames,surname FROM tblsystemuser WHERE userid='".mysqli_real_escape_string($con,$user)."' LIMIT 1"); if($person && $p=mysqli_fetch_assoc($person)){ $name=trim($p['firstname'].' '.$p['othernames'].' '.$p['surname']); } $notify=array(); staff_permission_notify_approvers($con,$approver,$name,$type,$start,$notify); $message='Permission request submitted. Notification sent to '.$notify['total'].' approver(s): '.$notify['sms_sent'].' SMS delivered, '.$notify['sms_failed'].' SMS failed.'; } else { $message='The request could not be submitted.'; $tone='bad'; } } }
}
$user=mysqli_real_escape_string($con,$_SESSION['USERID']); $history=@mysqli_query($con,"SELECT * FROM tblstaffpermissionrequest WHERE requester_id='$user' ORDER BY created_at DESC LIMIT 20");
$permissionDashboard = staff_permission_role()==='teacher' ? 'teacher-page.php' : (staff_permission_role()==='headmaster' ? 'headmaster-page.php' : 'assistant-head-academics-page.php');
?>
<div style="max-width:900px;margin:18px auto 0;padding:0 20px;box-sizing:border-box;"><a href="<?php echo staff_permission_escape($permissionDashboard); ?>" style="display:inline-block;padding:10px 15px;border-radius:7px;background:#0f4c75;color:#fff;font:700 15px Arial,sans-serif;text-decoration:none;">← Back to Dashboard</a></div>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Staff Permission Request</title><style>body{margin:0;background:#f3f6f8;color:#15283b;font:16px Arial}.wrap{max-width:900px;margin:35px auto;padding:0 20px}.card{background:#fff;padding:24px;border:1px solid #dce5eb;border-radius:10px;margin-bottom:20px}h1,h2{margin-top:0}label{display:block;font-weight:bold;margin:14px 0 6px}input,select,textarea{width:100%;box-sizing:border-box;padding:10px;border:1px solid #becbd5;border-radius:6px;font:inherit}textarea{min-height:120px}.button{margin-top:18px;padding:12px 17px;border:0;border-radius:7px;background:#0f4c75;color:#fff;font-weight:bold;cursor:pointer}.msg{padding:12px;border-radius:6px;margin-bottom:16px}.ok{background:#dcfce7;color:#166534}.bad{background:#fee2e2;color:#991b1b}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #dce5eb;text-align:left}.pending{color:#b45309}.approved{color:#15803d}.declined{color:#b91c1c}</style></head><body><main class="wrap"><div class="card"><h1>Staff Permission Request</h1><p>Request permission for absence, medical leave, official duty, late arrival, or another approved reason.</p><?php if($message!==''){ ?><div class="msg <?php echo $tone; ?>"><?php echo staff_permission_escape($message); ?></div><?php } ?><form method="post"><input type="hidden" name="csrf" value="<?php echo staff_permission_escape($_SESSION['staff_permission_csrf']); ?>"><label>Send request to</label><select name="approver_role"><?php foreach($options as $key=>$label){ ?><option value="<?php echo staff_permission_escape($key); ?>"><?php echo staff_permission_escape($label); ?></option><?php } ?></select><label>Permission type</label><select name="permission_type"><option>Absence from school</option><option>Medical permission</option><option>Official duty</option><option>Late arrival</option><option>Other permission</option></select><label>From</label><input type="datetime-local" name="start_datetime" required><label>To</label><input type="datetime-local" name="end_datetime" required><label>Reason</label><textarea name="reason" required></textarea><button class="button">Submit request</button></form></div><div class="card"><h2>My previous requests</h2><table><tr><th>Date</th><th>Type</th><th>Status</th><th>Decision note</th></tr><?php if($history){ while($row=mysqli_fetch_assoc($history)){ ?><tr><td><?php echo staff_permission_escape(date('d M Y',strtotime($row['created_at']))); ?></td><td><?php echo staff_permission_escape($row['permission_type']); ?></td><td class="<?php echo staff_permission_escape($row['status']); ?>"><?php echo staff_permission_escape(ucfirst($row['status'])); ?></td><td><?php echo staff_permission_escape($row['decision_note']); ?></td></tr><?php } } ?></table></div></main></body></html>
