<?php
if(!function_exists('transport_is_admin')){function transport_is_admin(){ return (isset($_SESSION['ACCESSLEVEL']) && $_SESSION['ACCESSLEVEL'] === 'administrator') || (isset($_SESSION['ACCESSLEVEL'], $_SESSION['SYSTEMTYPE']) && $_SESSION['ACCESSLEVEL'] === 'user' && $_SESSION['SYSTEMTYPE'] === 'AssistantHeadAdministration'); }}
if(!function_exists('transport_id')){function transport_id($prefix){return $prefix.strtoupper(substr(sha1(uniqid('',true)),0,18));}}
if(!function_exists('transport_ensure_tables')){function transport_ensure_tables($con){
@mysqli_query($con,"CREATE TABLE IF NOT EXISTS tbltransportvehicle(vehicleid VARCHAR(50) PRIMARY KEY,vehiclename VARCHAR(120) NOT NULL,registrationno VARCHAR(80) NOT NULL,capacity INT NOT NULL DEFAULT 0,driverid VARCHAR(100) NOT NULL DEFAULT '',assistantid VARCHAR(100) NOT NULL DEFAULT '',status VARCHAR(20) NOT NULL DEFAULT 'active',createdby VARCHAR(100) NOT NULL DEFAULT '',createdat DATETIME NOT NULL,UNIQUE KEY uq_registrationno(registrationno)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
@mysqli_query($con,"CREATE TABLE IF NOT EXISTS tbltransportroute(routeid VARCHAR(50) PRIMARY KEY,routename VARCHAR(150) NOT NULL,vehicleid VARCHAR(50) NOT NULL DEFAULT '',fee DECIMAL(12,2) NOT NULL DEFAULT 0,status VARCHAR(20) NOT NULL DEFAULT 'active',createdby VARCHAR(100) NOT NULL DEFAULT '',createdat DATETIME NOT NULL,UNIQUE KEY uq_routename(routename),KEY idx_vehicle(vehicleid)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
@mysqli_query($con,"CREATE TABLE IF NOT EXISTS tbltransportstop(stopid VARCHAR(50) PRIMARY KEY,routeid VARCHAR(50) NOT NULL,stopname VARCHAR(150) NOT NULL,pickuptime VARCHAR(20) NOT NULL DEFAULT '',sortorder INT NOT NULL DEFAULT 0,status VARCHAR(20) NOT NULL DEFAULT 'active',createdat DATETIME NOT NULL,KEY idx_route(routeid)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
@mysqli_query($con,"CREATE TABLE IF NOT EXISTS tblstudenttransport(assignmentid VARCHAR(50) PRIMARY KEY,userid VARCHAR(100) NOT NULL,routeid VARCHAR(50) NOT NULL,stopid VARCHAR(50) NOT NULL DEFAULT '',status VARCHAR(20) NOT NULL DEFAULT 'active',assignedby VARCHAR(100) NOT NULL DEFAULT '',assignedat DATETIME NOT NULL,UNIQUE KEY uq_student_transport(userid),KEY idx_route(routeid,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");}}
if(!function_exists('transport_route_capacity')){function transport_route_capacity($con,$routeId){$r=mysqli_query($con,"SELECT v.capacity,(SELECT COUNT(*) FROM tblstudenttransport st WHERE st.routeid=tr.routeid AND st.status='active') assigned FROM tbltransportroute tr LEFT JOIN tbltransportvehicle v ON v.vehicleid=tr.vehicleid WHERE tr.routeid='".mysqli_real_escape_string($con,$routeId)."' LIMIT 1");return $r?mysqli_fetch_assoc($r):null;}}
if(!function_exists('transport_assign_student')){function transport_assign_student($con,$studentId,$routeId,$stopId,$actor){transport_ensure_tables($con);$cap=transport_route_capacity($con,$routeId);if(!$cap)return array(false,'The selected route was not found.');if((int)$cap['capacity']>0&&(int)$cap['assigned']>=(int)$cap['capacity'])return array(false,'This route has reached vehicle capacity.');$s=mysqli_real_escape_string($con,$studentId);$r=mysqli_real_escape_string($con,$routeId);$p=mysqli_real_escape_string($con,$stopId);$a=mysqli_real_escape_string($con,$actor);$id=transport_id('TRA_');$ok=mysqli_query($con,"INSERT INTO tblstudenttransport(assignmentid,userid,routeid,stopid,status,assignedby,assignedat) VALUES('$id','$s','$r','$p','active','$a',NOW()) ON DUPLICATE KEY UPDATE routeid='$r',stopid='$p',status='active',assignedby='$a',assignedat=NOW()");return array($ok,$ok?'Student transport assignment saved.':'Could not save the transport assignment.');}}
?>
