<?php /* Ayirebi Senior High School public website */ ?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Ayirebi Senior High School — inspiring character, scholarship and service in the Eastern Region of Ghana.">
  <title>Ayirebi Senior High School | Eastern Region, Ghana</title>
  <link rel="icon" type="image/png" href="logo/logo-transparent.png">
  <link rel="apple-touch-icon" href="logo/logo-transparent.png">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="school-site.css">
  <link rel="stylesheet" href="css/ayisec-shared-palette.css">
</head>
<body>
  <div class="topbar"><div class="shell topbar-inner"><span>Eastern Region, Ghana</span><span class="top-links"><a href="#contact">Contact us</a><a href="https://wa.me/233245065954?text=Hello%2C%20I%20need%20help%20with%20Ayirebi%20Senior%20High%20School." target="_blank" rel="noopener noreferrer">Need help?</a><a href="#admissions">Admissions</a></span></div></div>
  <header class="header" id="home"><div class="shell nav-wrap">
    <a class="brand" href="#home" aria-label="Ayirebi Senior High School home"><span class="crest"><img src="logo/logo-transparent.png" alt="Ayirebi Senior High School logo"></span><span><strong>Ayirebi</strong><small>Senior High School</small></span></a>
    <button class="menu-toggle" aria-label="Open navigation" aria-expanded="false"><span></span><span></span></button>
    <nav class="nav" aria-label="Main navigation"><a href="#about">About</a><a href="#academics">Academics</a><a href="#life">Student life</a><a href="#news">News</a><a href="#contact">Contact</a><a class="nav-cta" href="index.php#portal-login">Portal login</a></nav>
  </div></header>

  <main>
    <section class="hero"><div class="hero-shade"></div><div class="shell hero-content">
      <p class="eyebrow light">Rooted in purpose. Ready for tomorrow.</p>
      <h1>A place to learn,<br><em>lead and belong.</em></h1>
      <p class="hero-copy">At Ayirebi Senior High School, every learner is challenged, supported and prepared to make a meaningful contribution to Ghana and the world.</p>
      <div class="hero-actions"><a class="button button-gold" href="index.php#portal-login">Portal login <span>→</span></a><a class="text-link" href="#about">Discover our story <span>↓</span></a></div>
    </div><img class="hero-3d-logo" src="logo/logo-transparent.png" alt="" aria-hidden="true"><div class="hero-note"><span class="note-line"></span><span>Character · Scholarship · Service</span></div></section>

    <section class="welcome" id="about"><div class="shell split-grid">
      <div><p class="eyebrow">Welcome to Ayirebi SHS</p><h2>Education with a<br><em>larger purpose.</em></h2></div>
      <div class="welcome-copy"><p>We are a vibrant co-educational senior high school in Ghana’s Eastern Region. Our community brings together committed teachers, curious learners and supportive families around one enduring belief: education should open minds and strengthen character.</p><a class="arrow-link" href="#academics">Learn about the school <span>→</span></a></div>
    </div></section>

    <section class="leadership" aria-labelledby="leadership-title"><div class="shell leadership-grid"><div class="leadership-photo"><img src="images/websiteimages/Headmater.jpg" alt="Ayirebi Senior High School headmaster recognising students at the Academic Excellence Awards"></div><div class="leadership-message"><p class="eyebrow light">Leadership at Ayirebi</p><h2 id="leadership-title">Every achievement<br>deserves to be <em>seen.</em></h2><p>At AYISEC, leadership is close to the student experience. We celebrate effort, recognise excellence and encourage every learner to become confident in their own ability.</p><span class="message-signoff">The Headmaster<br><small>Ayirebi Senior High School</small></span></div></div></section>
    <div class="shell leadership-moments" aria-label="Leadership moments"><figure><img src="images/websiteimages/Headmaster%20and%20students.jpg" alt="Headmaster with Ayirebi Senior High School students"><figcaption>Celebrating our outstanding students</figcaption></figure><figure><img src="images/websiteimages/Head2.jpg" alt="Ayirebi Senior High School leadership meeting"><figcaption>Leading through partnership</figcaption></figure></div>
    <section class="values"><div class="shell values-grid"><div class="value-intro"><p class="eyebrow light">What guides us</p><h2>One school.<br><em>Endless potential.</em></h2></div><article><span>01</span><h3>Academic ambition</h3><p>Rigorous teaching, purposeful study and a culture that celebrates progress.</p></article><article><span>02</span><h3>Whole-person growth</h3><p>Confidence, discipline and practical skills developed inside and beyond the classroom.</p></article><article><span>03</span><h3>Community spirit</h3><p>A respectful, inclusive environment where every learner is known and valued.</p></article></div></section>

    <section class="academics" id="academics"><div class="shell"><div class="section-heading"><div><p class="eyebrow">Learning at Ayirebi</p><h2>Find the path that<br><em>moves you forward.</em></h2></div><p>Our programmes balance strong academic foundations with the skills and experiences students need for life after school.</p></div><div class="programme-grid">
      <article class="programme programme-feature"><span class="programme-icon">⌁</span><h3>Agricultural Science</h3><p>Building analytical thinkers and future innovators through inquiry-led learning.</p><a href="#contact" aria-label="Ask about General Science">Explore <span>→</span></a></article>
      <article class="programme"><span class="programme-icon">◫</span><h3>General Arts</h3><p>Understanding people, society and ideas through engaging, relevant study.</p><a href="#contact" aria-label="Ask about General Arts">Explore <span>→</span></a></article>
      <article class="programme"><span class="programme-icon">◈</span><h3>Business</h3><p>Equipping enterprising students with practical financial and commercial insight.</p><a href="#contact" aria-label="Ask about Business">Explore <span>→</span></a></article>
      <article class="programme"><span class="programme-icon">✦</span><h3>Visual Arts</h3><p>Giving creative expression a home through craft, design and imagination.</p><a href="#contact" aria-label="Ask about Visual Arts">Explore <span>→</span></a></article>
      <article class="programme"><span class="programme-icon">⌂</span><h3>Home Economics</h3><p>Developing practical life skills, creativity and confident entrepreneurship.</p><a href="#contact" aria-label="Ask about Home Economics">Explore <span>→</span></a></article>
    </div></div></section>

    <section class="life" id="life"><div class="life-photo"></div><div class="life-panel"><p class="eyebrow">Life beyond lessons</p><h2>Every day is a chance to grow.</h2><p>From houses and clubs to sports, leadership and service, students discover their voice while forming friendships that last.</p><div class="life-points"><span>Clubs & societies</span><span>Sports & wellness</span><span>Leadership & service</span></div><a class="button button-outline" href="#contact">Experience student life <span>→</span></a></div></section>

    <section class="campus-gallery" aria-labelledby="campus-title"><div class="shell"><div class="gallery-heading"><div><p class="eyebrow">Our campus</p><h2 id="campus-title">Proudly <em>Ayirebi.</em></h2></div><p>From our green compound to our full school gatherings, every space reflects the energy and unity of the AYISEC family.</p></div><div class="gallery-grid"><figure class="gallery-wide"><img src="images/websiteimages/Campus1.jpg" alt="Students on the Ayirebi Senior High School campus"><figcaption>Welcome to the AYISEC campus</figcaption></figure><figure><img src="images/websiteimages/Culture1.jpg" alt="Students performing a cultural dance at Ayirebi Senior High School"><figcaption>Culture, rhythm and confidence</figcaption></figure><figure><img src="images/websiteimages/Sports3.jpg" alt="Students gathered at Ayirebi Senior High School"><figcaption>One proud school community</figcaption></figure></div></div></section>
    <section class="teachers" id="teachers"><div class="shell"><div class="section-heading"><div><p class="eyebrow">The people behind the progress</p><h2>Guidance that goes<br><em>beyond the classroom.</em></h2></div><p>Our teachers and support staff make AYISEC a place where students are encouraged to work hard, aim high and belong.</p></div><div class="teacher-grid"><article class="teacher"><img src="images/websiteimages/Teacher2.jpg" alt="Ayirebi Senior High School teaching and support staff"><div><p class="teacher-role">Our staff community</p><h3>Teaching with purpose</h3><p>Committed educators working together to help every learner make progress.</p></div></article><article class="teacher"><img src="images/websiteimages/Teachers1.jpg" alt="Ayirebi Senior High School staff at a school event"><div><p class="teacher-role">Guidance & mentorship</p><h3>Care that builds confidence</h3><p>Adults who see potential in young people and help them grow with discipline.</p></div></article><article class="teacher"><img src="images/websiteimages/Teachers3.jpg" alt="Ayirebi Senior High School teachers and students"><div><p class="teacher-role">Learning together</p><h3>Mentors for the future</h3><p>A supportive school culture built on respect, aspiration and shared success.</p></div></article></div></div></section>
    <section class="admissions" id="admissions"><div class="shell admissions-inner"><div><p class="eyebrow light">Joining our community</p><h2>Your next chapter<br>starts <em>here.</em></h2></div><div><p>We welcome families seeking a school where high expectations meet genuine care. Start your Ayirebi journey today.</p><a class="button button-gold" href="online-admission.php">Apply for admission <span>→</span></a><a class="admission-link" href="#contact">Speak with admissions <span>→</span></a></div></div></section>

    <section class="news" id="news"><div class="shell"><div class="news-header"><div><p class="eyebrow">AYISEC in focus</p><h2>Our moments. Our pride.</h2></div><a class="arrow-link" href="#gallery">View photo gallery <span>↓</span></a></div><div class="news-grid"><article><div class="news-image news-one"></div><p class="date">ACHIEVEMENT · AYISEC</p><h3>Celebrating the students who represent our school with pride.</h3><a href="#gallery">View gallery <span>→</span></a></article><article><div class="news-image news-two"></div><p class="date">SPORT · AYISEC</p><h3>Teamwork, discipline and the joy of competing together.</h3><a href="#gallery">View gallery <span>→</span></a></article><article><div class="news-image news-three"></div><p class="date">SCHOOL LIFE · AYISEC</p><h3>Creating memories that bring our school family together.</h3><a href="#gallery">View gallery <span>→</span></a></article></div></div></section>
    <?php $galleryImages = glob('images/websiteimages/*.{jpg,jpeg,png,JPG,JPEG,PNG}', GLOB_BRACE); sort($galleryImages, SORT_NATURAL | SORT_FLAG_CASE); ?>
    <section class="full-gallery" id="gallery" aria-labelledby="gallery-title"><div class="shell"><div class="gallery-title"><div><p class="eyebrow">The AYISEC gallery</p><h2 id="gallery-title">See our school<br><em>come alive.</em></h2></div><p>Explore our people, achievements, traditions, events and everyday life at Ayirebi Senior High School.</p></div><div class="gallery-wall"><?php foreach ($galleryImages as $image): $name = pathinfo($image, PATHINFO_FILENAME); $label = ucwords(str_replace(array('-', '_'), ' ', $name)); ?><button class="gallery-item" type="button" data-image="<?php echo htmlspecialchars($image, ENT_QUOTES, 'UTF-8'); ?>" data-label="<?php echo htmlspecialchars($label, ENT_QUOTES, 'UTF-8'); ?>"><img src="<?php echo htmlspecialchars($image, ENT_QUOTES, 'UTF-8'); ?>" alt="Ayirebi Senior High School — <?php echo htmlspecialchars($label, ENT_QUOTES, 'UTF-8'); ?>"><span><?php echo htmlspecialchars($label, ENT_QUOTES, 'UTF-8'); ?></span></button><?php endforeach; ?></div></div></section>
  </main>
  <section class="social-connect" aria-labelledby="social-title"><div class="shell social-connect-inner"><div><p class="eyebrow light">Stay in the AYISEC loop</p><h2 id="social-title">Follow our school<br><em>everywhere.</em></h2></div><div class="social-connect-links"><a href="https://www.facebook.com/Ayirebiseniorhighschool/" target="_blank" rel="noopener noreferrer"><b>f</b><span>Facebook<small>@AyirebiSeniorHighSchool</small></span><i>&#8599;</i></a><a href="https://www.tiktok.com/search?q=Official%20Ayisec%20Tv" target="_blank" rel="noopener noreferrer"><b>TT</b><span>TikTok<small>Official Ayisec Tv</small></span><i>&#8599;</i></a><a href="https://wa.me/233245065954?text=Hello%2C%20I%20need%20help%20with%20Ayirebi%20Senior%20High%20School." target="_blank" rel="noopener noreferrer"><b>WA</b><span>WhatsApp<small>+233 24 506 5954</small></span><i>&#8599;</i></a></div></div></section>

  <footer id="contact"><div class="shell footer-grid"><div class="footer-brand"><a class="brand" href="#home"><span class="crest"><img src="logo/logo.png" alt="Ayirebi Senior High School logo"></span><span><strong>Ayirebi</strong><small>Senior High School</small></span></a><p>Inspiring capable, compassionate young people from the Eastern Region of Ghana.</p></div><div><h4>Explore</h4><a href="#about">About us</a><a href="#academics">Academics</a><a href="#life">Student life</a><a href="#teachers">Our teachers</a><a href="#admissions">Admissions</a></div><div><h4>Contact</h4><p>Ayirebi, Eastern Region<br>Ghana</p><a href="tel:+233000000000">+233 (0) 24 560 5120</a><a href="mailto:info@ayirebishs.edu.gh">ayirebishs@ges.gov.gh</a></div><div><h4>Stay connected</h4><p>Receive school news, events and admissions updates.</p><form class="subscribe" onsubmit="event.preventDefault(); this.querySelector('input').value='Thank you for subscribing!';"><input aria-label="Email address" type="email" placeholder="Your email address" required><button aria-label="Subscribe">→</button></form></div></div><div class="shell footer-bottom"><span>© 2026 Ayirebi Senior High School</span><span>Eastern Region · Ghana</span></div></footer>
  <div class="platform-powered"><span>Powered by</span><a class="tokaa-powered-link" href="https://tokaatechconsult.com/" target="_blank" rel="noopener noreferrer" aria-label="Visit Tokaa Tech Consult"><img src="images/Tokaa%20Logo.png" alt="Tokaa Tech Consult"><strong>Tokaa Tech Consult</strong></a><span class="platform-divider">|</span><img src="images/LiveCampus.png" alt="LiveCampus"></div>
  <a class="website-help-fab" href="https://wa.me/233245065954?text=Hello%2C%20I%20need%20help%20with%20Ayirebi%20Senior%20High%20School." target="_blank" rel="noopener noreferrer" aria-label="Get help on WhatsApp"><span>Need help?</span><b>WA</b></a>
  <script src="school-site.js"></script>
</body>
</html>
